services:
  minecraft_whitelist_form:
    image: ghcr.io/fachschaft-informatik-nordakademie/minecraft_whitelist_form:latest
    restart: unless-stopped
    container_name: minecraft_whitelist_form
    volumes:
      - mcwlf_data:/app/instance
    ports:
      - "80:80"
    environment:
      - MCWLF_BASE_URL=
      - MCWLF_EXAROTON_API_TOKEN=
      - MCWLF_EXAROTON_SERVER_ID=
      - MCWLF_ADMIN_SECRET=
      - MCWLF_MAIL_SERVER=
      - MCWLF_MAIL_PORT=
      - MCWLF_MAIL_USE_TLS=
      - MCWLF_MAIL_USE_SSL=
      - MCWLF_MAIL_USERNAME=
      - MCWLF_MAIL_PASSWORD=
      - MCWLF_MAIL_DEFAULT_SENDER=
      #- MCWLF_DATABASE= # optional, default "./instance/db.sqlite3" (routed to volume)
      #- MCWLF_ALLOWED_MAIL_SUFFIXES= # optional, default ["@nordakademie.de", "@nordakademie.org"]

volumes:
  mcwlf_data: